# Generated by Django 3.1.4 on 2020-12-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='hederline',
            new_name='headerline',
        ),
    ]
