# Generated by Django 3.1.4 on 2020-12-24 20:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='fb_handle',
            field=models.CharField(max_length=255),
        ),
    ]
